name: "Welcome notice for external pull requests"
on:
    pull_request:
        types:
            - opened

jobs:
    triage:
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PR: ${{ github.event.pull_request.html_url }}
        if: >-
            ${{ github.event_name == 'pull_request' &&
                github.event.pull_request.head.repo.full_name != 'mendix/web-widgets' }}
        runs-on: ubuntu-latest
        steps:
            - name: "First welcome comment"
              run: |
                  gh pr edit $PR --add-label 'external'
                  gh pr comment $PR --body-file ./.github/pull_request_welcome_message.md
